[tasks.watch]
description = "watch for changes and rebuild / rerun release"
run = "watchexec -w src -r cargo run --release"
alias = "w"

[tasks.test_watch]
description = "watch for changes and test"
run = "watchexec -w src -w tests -r cargo test --release"
alias = "t"

[tasks.build]
description = "build docker image"
run = "docker compose build"

[tasks.docker]
description = "build and run docker image"
depends = ["build"]
run = "docker compose up -d"
alias = "d"

[tasks.release]
description = "set new release version"
run = "cargo release"
alias = "r"

[env]
# fnaf api
FACE_DIR = "./faces"
FNAF_HOST = "0.0.0.0"
FNAF_PORT = 9638
FNAF_ENCODER_QUALITY = "70.0"

# discord gateway
# (comments below to be set in environment or mise.local.toml)
GATEWAY_HANDLER = false
DISCORD_TOKEN = { required = true }
# DISCORD_TOKEN = ""

# discord interaction api
# (comments below to be set in environment or mise.local.toml)
INTERACTION_HANDLER = false
DISCORD_PUBLIC_KEY = { required = false }
DISCORD_CLIENT_ID = { required = false }
DISCORD_CLIENT_SECRET = { required = false }
# DISCORD_PUBLIC_KEY = ""
# DISCORD_CLIENT_ID = ""
# DISCORD_CLIENT_SECRET = ""
